/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation( "org.jetbrains.kotlin:kotlin-test-junit5:1.9.22")
    implementation("org.jetbrains.kotlin:kotlin-serialization:1.9.22")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.22")
    implementation("com.squareup.okhttp3:okhttp:5.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.5.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
    implementation("org.mongodb:mongodb-driver-kotlin-coroutine:5.0.0")
    implementation("org.mongodb:bson-kotlinx:5.0.0")
    implementation("io.github.oshai:kotlin-logging-jvm:5.0.2")
    implementation("org.slf4j:slf4j-api:1.7.25")
    implementation("ch.qos.logback:logback-classic:1.5.18")
    implementation("org.jetbrains.exposed:exposed-core:1.0.0-beta-4")
    implementation("org.jetbrains.exposed:exposed-jdbc:1.0.0-beta-4")
    implementation("org.jetbrains.exposed:exposed-dao:1.0.0-beta-4")
    implementation("org.jetbrains.exposed:exposed-json:1.0.0-beta-4")
    implementation("org.postgresql:postgresql:42.7.7")
}

group = "com.code.catalyst"
version = "1.0"
description = "Backend Data Aggregator"
java.sourceCompatibility = JavaVersion.VERSION_21


//tasks.withType<Javaimplementation>() {
//    options.encoding = "UTF-8"
//}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("MainKt")
}

